### ISSUE TITLE
Dark mode leads to inconsistent display

### ISSUE THREAD

**Issue by nymphbox** [innoTUgrid/frontend#102]
Using system dark mode on mac os [Monterey 12.5.1]  and opening the frontend with chrome [120.0.6099.71 (arm64)] 
makes the graphs use a dark color scheme while the rest of the page is still in light mode.

<img width="1255" alt="Screenshot 2023-12-13 at 12 03 49" src="https://github.com/innoTUgrid/frontend/assets/74098474/d2b60ff7-7059-4719-b8ed-cd672919f060">

**Comment by gretamaltsenko** [comment]
will not be fixed
