### ISSUE TITLE
Sankey diagram: residual energy

### ISSUE THREAD

**Issue by gretamaltsenko** [innoTUgrid/frontend#225]
Wir haben nur einen Consumer, die restlichen Daten als residual energy zusammenfassen, damit sie nicht optisch verloren gehen. 
Wenn mehrere consumer da sind, sollte diese auch angezeigt werden. die über geblieber energy dann als residual

**Comment by Nastassia-lk** [comment]
@gretamaltsenko ich denke @Tobiasloch würde besser für diesen issue passen, da er sich mit der Logik von Sankey schon auskennt.

**Comment by gretamaltsenko** [comment]
@Tobiasloch könntest du übernehmen?

**Comment by Tobiasloch** [comment]
Wurde in 039dbb0d2787d03f3b2c9716f4759415a8ffb096 implementiert
