### ISSUE TITLE
Overview page: change ratio of diagrams

### ISSUE THREAD

**Issue by gretamaltsenko** [innoTUgrid/frontend#232]
Gerade nehmen die 2 Reihen an KPIs ca. 50% des Bildschirmes ein. Chantal hat gebeten, das Ratio zu ändern, so dass die Diagramme oben links und rechts größer sind und die KPI-Reihen unten 30-50% an Platz einnehmen.

**Comment by Nastassia-lk** [comment]
@gretamaltsenko auf dem kleinen Bildschirm sieht es wie davor aus (damit alle Diagramme immer noch drauf passen): 
<img width="1500" alt="Bildschirmfoto 2024-02-09 um 22 14 03" src="https://github.com/innoTUgrid/frontend/assets/53143036/2b48e46f-4756-4041-8c68-933be2f18416">

Auf großem Bildschirm ist Ratio 70:30: 
![Bildschirmfoto 2024-02-09 um 22 13 21](https://github.com/innoTUgrid/frontend/assets/53143036/5ce6b5a3-08ea-46d6-90e1-a506f7184ee8)
