### ISSUE TITLE
GRI report: compare data with overview page data

### ISSUE THREAD

**Issue by gretamaltsenko** [innoTUgrid/frontend#245]
@chaboden

**Comment by chaboden** [comment]
Daten die falsch/unstimmig sind

- [ ]  total consumption: Wert von der kpi auf der overview page (2019: 10,26 GWh) ist ein deutlich anderer Wert als auf der Reporting page (2019: 2,3 GWh)
- [ ] total emissions: Werte von 2019 und 2020 auf der emissions page unten links weichen deutlich ab von den Werten der reporting page oder der kpi der overview page

**Comment by Tobiasloch** [comment]
total emissions in gri 305-1 did not include biogas before. Fixed in fa01f2cdc74fc721283f0c3c6bfd7ff5963dbbf3
