### ISSUE TITLE
KPI rows: text can not be seen

### ISSUE THREAD

**Issue by gretamaltsenko** [innoTUgrid/frontend#259]
Die Sicht auf die KPIs ist wie folgt:

![Image](https://github.com/innoTUgrid/frontend/assets/149379678/8b4ff17c-47d5-4512-a30e-b74d948c174a)

Der Text soll vollständig sichtbar sein. Darüber hinaus soll die 2 Reihe an KPIs reduzierte Textgröße im Vergleich zur 1. Reihe haben.

**Comment by Tobiasloch** [comment]
see 583dfa2
